import { describe, expect, it } from "vitest";
import { ipcChannels } from "../src/shared/ipc-channels.js";

describe("IPC channels", () => {
  it("exposes only the current generic workbench channels", () => {
    expect(ipcChannels).toEqual({
      listRoots: "config:listRoots",
      pickProjectFolder: "config:pickProjectFolder",
      addProject: "config:addProject",
      removeProject: "config:removeProject",
      renameProject: "config:renameProject",
      setAppearanceTheme: "config:setAppearanceTheme",
      setCodeGraphAutoMaintain: "config:setCodeGraphAutoMaintain",
      scanProjects: "projects:scan",
      getProjectDetail: "projects:getDetail",
      listProjectFiles: "projects:listFiles",
      readProjectFile: "files:read",
      writeProjectFile: "files:write",
      deleteProjectFile: "files:delete",
      renameProjectFile: "files:rename",
      codeGraphGetStatus: "codegraph:getStatus",
      codeGraphEnsureStatus: "codegraph:ensureStatus",
      createTerminal: "terminal:create",
      terminalInput: "terminal:input",
      resizeTerminal: "terminal:resize",
      closeTerminal: "terminal:close",
      terminalData: "terminal:data",
      terminalUpdate: "terminal:update",
      terminalExit: "terminal:exit",
      createBrowser: "browser:create",
      browserNavigate: "browser:navigate",
      browserResize: "browser:resize",
      browserClose: "browser:close",
      browserGoBack: "browser:goBack",
      browserGoForward: "browser:goForward",
      browserReload: "browser:reload",
      browserUpdate: "browser:update",
      protocolGetTasks: "protocol:getTasks",
      protocolGetStatus: "protocol:getStatus",
      protocolInstall: "protocol:install",
      protocolEnable: "protocol:enable",
      protocolUninstall: "protocol:uninstall",
      protocolResolveIdentity: "protocol:resolveIdentity",
      protocolSyncNow: "protocol:syncNow",
      protocolUpdateHarness: "protocol:updateHarness",
      protocolTasksChanged: "protocol:tasksChanged",
      knowledgeSiteGenerate: "knowledgeSite:generate",
      knowledgeSiteGetPath: "knowledgeSite:getPath",
      listAgentClis: "agents:listClis",
      listInstallRecipes: "agents:listInstallRecipes",
      installTool: "agents:installTool",
      installLog: "agents:installLog",
      agentStatus: "agents:status",
      pathExistsOnTarget: "projects:pathExists",
      listPlugins: "plugins:list",
      setPluginEnabled: "plugins:setEnabled",
      readDiagnostics: "diagnostics:read",
      usageGetSummary: "usage:getSummary",
      usageGetReport: "usage:getReport",
      dockBadgeUpdate: "dock:badgeUpdate",
      contentReady: "app:contentReady",
      setHooksEnabled: "agents:setHooksEnabled",
      hookGetSessions: "hooks:getSessions",
      createWorktree: "git:createWorktree",
      openExternal: "shell:openExternal",
      islandGetAllSessions: "island:getAllSessions",
      islandFocusSession: "island:focusSession",
      islandTabsSync: "island:tabsSync",
      recordSessionPrompt: "session:recordPrompt",
      recordPromptHistoryEntry: "session:recordPromptEntry",
      loadSessionPromptHistory: "session:loadPromptHistory",
    });
    expect(Object.values(ipcChannels).some((channel) => channel.startsWith("harness:"))).toBe(false);
  });
});
