import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { installHarness, isHarnessInstalled } from "../src/main/teamwork-harness.js";
import { makeTempRoot, writeJson, writeText } from "./helpers.js";

const execFileAsync = promisify(execFile);

const harnessOptions = {
  githubLogin: "SharkUI",
  githubUserId: 3960864,
  machineId: "abcdef",
  agent: "codex",
  repo: "SharkUI/AIBF",
};

describe("teamwork harness install", () => {
  it("writes local harness files and ignored root adapters", async () => {
    const root = await makeTempRoot("teamwork-harness");
    const repo = await createRealGitRepoFixture(root);

    await installHarness(repo, harnessOptions);

    await expect(isHarnessInstalled(repo)).resolves.toBe(true);
    await expect(fs.readFile(path.join(repo, "AGENTS.md"), "utf8")).resolves.toContain("sharkbay-generated: true");
    await expect(fs.readFile(path.join(repo, ".sharkbay", "harness", "protocol.md"), "utf8")).resolves.toContain("Repo: SharkUI/AIBF");
    await expect(fs.readFile(path.join(repo, ".git", "info", "exclude"), "utf8")).resolves.toContain("/AGENTS.md");
  });

  it("refuses to overwrite an existing user root instruction file", async () => {
    const root = await makeTempRoot("teamwork-harness-conflict");
    const repo = await createRealGitRepoFixture(root);
    const agentsPath = path.join(repo, "AGENTS.md");
    await writeText(agentsPath, "# Existing agent rules\n");

    await expect(installHarness(repo, harnessOptions)).rejects.toThrow(/AGENTS\.md/);
    await expect(fs.readFile(agentsPath, "utf8")).resolves.toBe("# Existing agent rules\n");
    await expect(isHarnessInstalled(repo)).resolves.toBe(false);
  });

  it("refuses to install into a directory that is not a git worktree", async () => {
    const root = await makeTempRoot("teamwork-harness-no-git");
    const repo = path.join(root, "plain-folder");
    await fs.mkdir(repo, { recursive: true });

    await expect(installHarness(repo, harnessOptions)).rejects.toThrow(/requires a Git repository/);
    await expect(fs.stat(path.join(repo, ".git")).catch(() => null)).resolves.toBeNull();
    await expect(isHarnessInstalled(repo)).resolves.toBe(false);
  });

  it("updates root adapters that were generated by SharkBay", async () => {
    const root = await makeTempRoot("teamwork-harness-generated");
    const repo = await createRealGitRepoFixture(root);
    const agentsPath = path.join(repo, "AGENTS.md");
    await writeText(agentsPath, "<!-- sharkbay-generated: true -->\nold adapter\n");

    await installHarness(repo, harnessOptions);

    const content = await fs.readFile(agentsPath, "utf8");
    expect(content).toContain("This worktree uses SharkBay Teamwork.");
    expect(content).not.toContain("old adapter");
  });
});

async function createRealGitRepoFixture(root: string, name = "FixtureApp"): Promise<string> {
  const repo = path.join(root, name);
  await fs.mkdir(repo, { recursive: true });
  await writeJson(path.join(repo, "package.json"), { name: name.toLowerCase(), version: "1.0.0" });
  await execFileAsync("git", ["init"], { cwd: repo });
  return repo;
}
